Repository farmingsoon/BE, pull requests merged in 2024-01, with the labels that each got.

#1 API 응답 형식 구현
  src/main/java/com/api/farmingsoon/common/response/Response.java
  src/main/java/com/api/farmingsoon/common/security/SecurityConfig.java
  src/main/java/com/api/farmingsoon/domain/member/controller/MemberController.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ✨ Feature

#3 예외 공통 처리 및 에러 코드 작성
  src/main/java/com/api/farmingsoon/common/exception/CustomException.java
  src/main/java/com/api/farmingsoon/common/exception/ErrorCode.java
  src/main/java/com/api/farmingsoon/common/exception/GlobalExceptionHandler.java
  src/main/java/com/api/farmingsoon/common/exception/custom_exception/AwsS3Exception.java
  src/main/java/com/api/farmingsoon/common/exception/custom_exception/BadRequestException.java
  src/main/java/com/api/farmingsoon/common/exception/custom_exception/DuplicateException.java
  src/main/java/com/api/farmingsoon/common/exception/custom_exception/ForbiddenException.java
  src/main/java/com/api/farmingsoon/common/exception/custom_exception/InvalidException.java
  src/main/java/com/api/farmingsoon/common/exception/custom_exception/NotFoundException.java
  src/main/java/com/api/farmingsoon/common/exception/custom_exception/NotMatchException.java
  src/main/java/com/api/farmingsoon/common/response/Response.java
Labels: ✨ Feature

#4 CI/CD test를 위한 main merge
  .github/workflows/work.yml
  Dockerfile
  src/main/java/com/api/farmingsoon/common/exception/CustomException.java
  src/main/java/com/api/farmingsoon/common/exception/ErrorCode.java
  src/main/java/com/api/farmingsoon/common/exception/GlobalExceptionHandler.java
  src/main/java/com/api/farmingsoon/common/exception/custom_exception/AwsS3Exception.java
  src/main/java/com/api/farmingsoon/common/exception/custom_exception/BadRequestException.java
  src/main/java/com/api/farmingsoon/common/exception/custom_exception/DuplicateException.java
  src/main/java/com/api/farmingsoon/common/exception/custom_exception/ForbiddenException.java
  src/main/java/com/api/farmingsoon/common/exception/custom_exception/InvalidException.java
  src/main/java/com/api/farmingsoon/common/exception/custom_exception/NotFoundException.java
  src/main/java/com/api/farmingsoon/common/exception/custom_exception/NotMatchException.java
  src/main/java/com/api/farmingsoon/common/response/Response.java
Labels: 🚀deploy

#6 회원가입 및 로그인 기능 구현1(JWT)
  build.gradle
  src/main/java/com/api/farmingsoon/common/exception/ErrorCode.java
  src/main/java/com/api/farmingsoon/common/interceptor/AuthenticationInterceptor.java
  src/main/java/com/api/farmingsoon/common/redis/RedisConfig.java
  src/main/java/com/api/farmingsoon/common/redis/RedisService.java
  src/main/java/com/api/farmingsoon/common/security/config/SecurityConfig.java
  src/main/java/com/api/farmingsoon/common/security/jwt/JwtProvider.java
  src/main/java/com/api/farmingsoon/common/security/jwt/JwtTokenRes.java
  src/main/java/com/api/farmingsoon/common/util/JwtUtils.java
  src/main/java/com/api/farmingsoon/domain/member/controller/MemberController.java
  src/main/java/com/api/farmingsoon/domain/member/model/Member.java
  src/main/java/com/api/farmingsoon/domain/member/model/MemberRole.java
  src/main/java/com/api/farmingsoon/domain/member/repository/MemberRepository.java
  src/main/java/com/api/farmingsoon/domain/member/service/MemberService.java
Labels: ✨ Feature

#10 회원 가입 및 폼 로그인 기능 구현
  src/main/java/com/api/farmingsoon/common/exception/ErrorCode.java
  src/main/java/com/api/farmingsoon/common/interceptor/AuthenticationInterceptor.java
  src/main/java/com/api/farmingsoon/common/security/service/CustomUserDetailsService.java
  src/main/java/com/api/farmingsoon/domain/member/controller/MemberController.java
  src/main/java/com/api/farmingsoon/domain/member/dto/JoinRequest.java
  src/main/java/com/api/farmingsoon/domain/member/dto/LoginRequest.java
  src/main/java/com/api/farmingsoon/domain/member/dto/LoginResponse.java
  src/main/java/com/api/farmingsoon/domain/member/model/Member.java
  src/main/java/com/api/farmingsoon/domain/member/service/MemberService.java
Labels: ✨ Feature

#12 S3 이미지 업로드 기능 구현
  build.gradle
  src/main/java/com/api/farmingsoon/common/exception/ErrorCode.java
  src/main/java/com/api/farmingsoon/common/exception/custom_exception/S3Exception.java
  src/main/java/com/api/farmingsoon/common/s3/config/S3Config.java
  src/main/java/com/api/farmingsoon/common/s3/service/S3Service.java
  src/main/java/com/api/farmingsoon/common/util/MultipartFileUtils.java
Labels: ✨ Feature

#14 Item APi 개발
  build.gradle
  src/main/java/com/api/farmingsoon/common/auditing/AuditingConfig.java
  src/main/java/com/api/farmingsoon/common/auditing/BaseTimeEntity.java
  src/main/java/com/api/farmingsoon/common/event/UploadImagesRollbackEvent.java
  src/main/java/com/api/farmingsoon/common/exception/ErrorCode.java
  src/main/java/com/api/farmingsoon/common/listener/ImageEventListener.java
  src/main/java/com/api/farmingsoon/common/querydsl/querydslConfig.java
  src/main/java/com/api/farmingsoon/common/s3/service/S3Service.java
  src/main/java/com/api/farmingsoon/common/security/config/SecurityConfig.java
  src/main/java/com/api/farmingsoon/common/util/AuthenticationUtils.java
  src/main/java/com/api/farmingsoon/common/util/TimeUtils.java
  src/main/java/com/api/farmingsoon/domain/image/domain/Image.java
  src/main/java/com/api/farmingsoon/domain/image/repository/ImageRepository.java
  src/main/java/com/api/farmingsoon/domain/image/service/ImageService.java
  src/main/java/com/api/farmingsoon/domain/item/controller/ItemController.java
  src/main/java/com/api/farmingsoon/domain/item/domain/Item.java
  src/main/java/com/api/farmingsoon/domain/item/domain/ItemStatus.java
  src/main/java/com/api/farmingsoon/domain/item/dto/ItemCreateRequest.java
  src/main/java/com/api/farmingsoon/domain/item/dto/ItemListResponse.java
  src/main/java/com/api/farmingsoon/domain/item/dto/ItemResponse.java
  src/main/java/com/api/farmingsoon/domain/item/dto/ItemWithPageResponse.java
  src/main/java/com/api/farmingsoon/domain/item/repository/ItemRepository.java
  src/main/java/com/api/farmingsoon/domain/item/repository/ItemRepositoryCustom.java
  src/main/java/com/api/farmingsoon/domain/item/repository/ItemRepositoryCustomImpl.java
  src/main/java/com/api/farmingsoon/domain/item/service/ItemService.java
  src/main/java/com/api/farmingsoon/domain/member/model/Member.java
Labels: ✨ Feature

#17 로그인 여부 확인 AOP적용 + 권한체킹 공통 처리
  src/main/java/com/api/farmingsoon/common/annotation/LoginChecking.java
  src/main/java/com/api/farmingsoon/common/aop/LoginCheckingAop.java
  src/main/java/com/api/farmingsoon/common/exception/ErrorCode.java
  src/main/java/com/api/farmingsoon/common/security/config/SecurityConfig.java
  src/main/java/com/api/farmingsoon/common/security/service/CustomUserDetailsService.java
  src/main/java/com/api/farmingsoon/common/util/AuthenticationUtils.java
  src/main/java/com/api/farmingsoon/common/util/JwtUtils.java
  src/main/java/com/api/farmingsoon/common/web/WebConfig.java
  src/main/java/com/api/farmingsoon/domain/item/controller/ItemController.java
  src/main/java/com/api/farmingsoon/domain/item/domain/Item.java
  src/main/java/com/api/farmingsoon/domain/item/service/ItemService.java
  src/main/java/com/api/farmingsoon/domain/member/controller/MemberController.java
  src/main/java/com/api/farmingsoon/domain/member/model/Member.java
Labels: ✨ Feature, ♻️ Refactor

#19 SSE를 이용한 실시간 알림 기능 구현
  src/main/java/com/api/farmingsoon/common/event/BidEndEvent.java
  src/main/java/com/api/farmingsoon/common/event/BidRegisterEvent.java
  src/main/java/com/api/farmingsoon/common/event/ItemSoldOutEvent.java
  src/main/java/com/api/farmingsoon/common/listener/NotificationEventListener.java
  src/main/java/com/api/farmingsoon/common/sse/SseEmitterRepository.java
  src/main/java/com/api/farmingsoon/common/sse/SseService.java
  src/main/java/com/api/farmingsoon/domain/notification/controller/NotificationController.java
  src/main/java/com/api/farmingsoon/domain/notification/dto/NotificationResponse.java
  src/main/java/com/api/farmingsoon/domain/notification/model/Notification.java
  src/main/java/com/api/farmingsoon/domain/notification/repository/NotificationRepository.java
  src/main/java/com/api/farmingsoon/domain/notification/service/NotificationService.java
Labels: ✨ Feature

#23 상품 좋아요, 입찰 기능 구현
  src/main/java/com/api/farmingsoon/common/exception/ErrorCode.java
  src/main/java/com/api/farmingsoon/common/init/DevInitData.java
  src/main/java/com/api/farmingsoon/domain/bid/controller/BidController.java
  src/main/java/com/api/farmingsoon/domain/bid/dto/BidRequest.java
  src/main/java/com/api/farmingsoon/domain/bid/dto/BidWithPageResponse.java
  src/main/java/com/api/farmingsoon/domain/bid/dto/BidsResponse.java
  src/main/java/com/api/farmingsoon/domain/bid/model/Bid.java
  src/main/java/com/api/farmingsoon/domain/bid/repository/BidRepository.java
  src/main/java/com/api/farmingsoon/domain/bid/service/BidService.java
  src/main/java/com/api/farmingsoon/domain/item/controller/ItemController.java
  src/main/java/com/api/farmingsoon/domain/item/domain/Item.java
  src/main/java/com/api/farmingsoon/domain/item/dto/ItemListResponse.java
  src/main/java/com/api/farmingsoon/domain/item/repository/ItemRepository.java
  src/main/java/com/api/farmingsoon/domain/like/controller/LikeController.java
  src/main/java/com/api/farmingsoon/domain/like/model/Like.java
  src/main/java/com/api/farmingsoon/domain/like/repository/LikeRepository.java
  src/main/java/com/api/farmingsoon/domain/like/service/LikeService.java
Labels: ✨ Feature

#24 웹소켓을 이용한 채팅 기능 구현
  build.gradle
  src/main/java/com/api/farmingsoon/common/exception/ErrorCode.java
  src/main/java/com/api/farmingsoon/common/websocket/WebSocketConfig.java
  src/main/java/com/api/farmingsoon/domain/chat/controller/ChatApiController.java
  src/main/java/com/api/farmingsoon/domain/chat/controller/ChatController.java
  src/main/java/com/api/farmingsoon/domain/chat/dto/ChatMessageRequest.java
  src/main/java/com/api/farmingsoon/domain/chat/dto/ChatResponse.java
  src/main/java/com/api/farmingsoon/domain/chat/model/Chat.java
  src/main/java/com/api/farmingsoon/domain/chat/repository/ChatRepository.java
  src/main/java/com/api/farmingsoon/domain/chat/service/ChatService.java
  src/main/java/com/api/farmingsoon/domain/chatroom/controller/ChatRoomController.java
  src/main/java/com/api/farmingsoon/domain/chatroom/dto/ChatRoomCreateRequest.java
  src/main/java/com/api/farmingsoon/domain/chatroom/dto/ChatRoomDetailResponse.java
  src/main/java/com/api/farmingsoon/domain/chatroom/dto/ChatRoomResponse.java
  src/main/java/com/api/farmingsoon/domain/chatroom/model/ChatRoom.java
  src/main/java/com/api/farmingsoon/domain/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/api/farmingsoon/domain/chatroom/service/ChatRoomService.java
  src/main/java/com/api/farmingsoon/domain/item/service/ItemService.java
Labels: ✨ Feature

#26 좋아요 기능 수정
  src/main/java/com/api/farmingsoon/common/init/DevInitData.java
  src/main/java/com/api/farmingsoon/domain/item/domain/Item.java
  src/main/java/com/api/farmingsoon/domain/like/model/Like.java
  src/main/java/com/api/farmingsoon/domain/like/service/LikeService.java
  src/main/resources/data.sql
Labels: ✨ Feature
